### ISSUE TITLE
Cannot run on Debian 12

### ISSUE THREAD

**Issue by bassstorm** [Flairmesh/FlooCast#2]
App cannot be run on Debian 12 using current README instructions.

1. Clone repo
2. Install `python3-pystray` and `python3-pyserial`
3. Run `main.py` and see an error

```
$ python3 main.py
Traceback (most recent call last):
  File "/home/username/App/FlooCast/main.py", line 17, in <module>
    from FlooDfuThread import FlooDfuThread
  File "/home/username/App/FlooCast/FlooDfuThread.py", line 9, in <module>
    from HidDfuAPI import HidDfu
ModuleNotFoundError: No module named 'HidDfuAPI'
```

Search for "HidDfuAPI" over the Internet gave me zero reults, so I installed `python3-hidapi`, but that didn't help.
Kindly advice what's actually missing.

**Comment by Flairmesh** [comment]
You can comment out this line since it references a library from Qualcomm used for upgrading the chip. Based on their license, it is not open source and can only be used on Windows. We will remove it in the next release.

**Comment by bassstorm** [comment]
Thanks, that did the trick :)
