### ISSUE TITLE
Make aptX Lossless optional

### ISSUE THREAD

**Issue by bassstorm** [Flairmesh/FlooCast#3]
In some cases user may prefer to use lower bitrate option instead of aptX Lossless:
* for more stable connection
* for lower battery drain

Unfortunately, only few headphones can disable HiRes in their app, e.g. Momentum 4 True Wireless. For many others there's no luck.

Please make aptX Lossless optional (same way as LE Audio), if that's not a hardware limitation.

**Comment by Flairmesh** [comment]
Okay, we’ll release an update soon. The new app will also display the real-time bitrate and RSSI for adaptive/lossless modes.

**Comment by bassstorm** [comment]
New release/firmware works like a charm on my end. Eternal thank you!
Please feel free to close the ticket when happy with testing on your end.
